### ISSUE TITLE
debugging the eyetracker object

### ISSUE THREAD

**Issue by ClementAbb** [Intrepid-2a/Distance#6]
I created the file ET_for_glasgow_test.py with a mininal implementation of the eye-tracking object for debugging purposes.

Using the latest version of the eye-tracker code to run this, I get the following error:
```
PS C:\Users\clementa\Desktop\templeton_gh\Distance> & "C:\Program Files\PsychoPy_2022\python.exe" .\ET_for_glasgow_test.py
pygame 2.1.0 (SDL 2.0.16, Python 3.8.10)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File ".\ET_for_glasgow_test.py", line 45, in <module>
    tracker = EyeTracker(tracker           = 'eyelink',
  File "C:\Users\clementa\Desktop\templeton_gh\Distance\..\EyeTracking\EyeTracking.py", line 63, in __init__
    self.setEyetracker(tracker)
  File "C:\Users\clementa\Desktop\templeton_gh\Distance\..\EyeTracking\EyeTracking.py", line 102, in setEyetracker
    self.setupEyeLink()
  File "C:\Users\clementa\Desktop\templeton_gh\Distance\..\EyeTracking\EyeTracking.py", line 325, in setupEyeLink
    if hasattr(self, colors):
NameError: name 'colors' is not defined
```

I can avoid this by replacing, in the eye-tracker code,
```
if hasattr(self, colors):
    if 'back' in self.colors.keys():
        color = self.colors['back']
    else:
        # what is a sensible default?
        color = [0,0,0]
        print('No color attribute, using PsychoPy default background color.')
```
by
`color = self.colors['back']`

But then I get a bit crazy.

First, I get this log:
```
PS C:\Users\clementa\Desktop\templeton_gh\Distance> & "C:\Program Files\PsychoPy_2022\python.exe" .\ET_for_glasgow_test.py
pygame 2.1.0 (SDL 2.0.16, Python 3.8.10)
Hello from the pygame community. https://www.pygame.org/contribute.html
../data/distance/eyetracking/test/
test_dist_LH_1
True
```

And two windows open, one with 'screen 1' displayed, the other one empty. The empty one is on top of the other so the result is an empty screen with the background color.

When I push a key, I see "screen 2" displayed (the eyetracker object somehow stops blocking the way) and this further log:
```
ERROR: DEVICE CONFIG ERRORS FOUND! IOHUB NOT LOADING DEVICE: psychopy.iohub.devices.eyetracker.hw.sr_research.eyelink
errors count 1:
        ('default_native_data_file_name', 'test_dist_LH_1')


not_found count 1:
        ('local_edf_dir', '../data/distance/eyetracking/test/')


## Device was not started by the ioHub Server: eyetracker.hw.sr_research.eyelink.EyeTracker
Error during device creation ....
Traceback (most recent call last):
  File "C:\Program Files\PsychoPy_2022\lib\site-packages\psychopy\iohub\server.py", line 716, in createNewMonitoredDevice
    raise ioHubError('Device config validation failed')
psychopy.iohub.errors.ioHubError: ioHubError:
Args: ('Device config validation failed',)

Error during device creation ....
Traceback (most recent call last):
  File "C:\Program Files\PsychoPy_2022\lib\site-packages\psychopy\iohub\server.py", line 716, in createNewMonitoredDevice
    raise ioHubError('Device config validation failed')
psychopy.iohub.errors.ioHubError: ioHubError:
Args: ('Device config validation failed',)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\PsychoPy_2022\lib\site-packages\psychopy\iohub\server.py", line 642, in _addDevices
    self.createNewMonitoredDevice(dev_cls_name, dev_conf) 
  File "C:\Program Files\PsychoPy_2022\lib\site-packages\psychopy\iohub\server.py", line 721, in createNewMonitoredDevice
    raise ioHubError('Error during device creation ....')
psychopy.iohub.errors.ioHubError: ioHubError:
Args: ('Error during device creation ....',)

GET_DEV_INTERFACE_ERROR: _getRPCInterface returned: None
```

When I enter another key to test calibration, it does crash with this error:
```
Traceback (most recent call last):
  File ".\ET_for_glasgow_test.py", line 68, in <module>
    tracker.calibrate()
  File "C:\Users\clementa\Desktop\templeton_gh\Distance\..\EyeTracking\EyeTracking.py", line 608, in __EL_calibrate
    result = self.tracker.runSetupProcedure()
  File "C:\Program Files\PsychoPy_2022\lib\site-packages\psychopy\iohub\client\__init__.py", line 153, in __getattr__
    raise AttributeError(self, name)
AttributeError: (<psychopy.iohub.client.ioHubDeviceView object at 0x0000029A90D3C700>, 'runSetupProcedure')
```

I was thinking this had something to do with the logfiles, so I tried without recording them by commenting out
``` 
        if self.storefiles:
            eyetracker_config['default_native_data_file_name'] = self.filename  # correct extention is added by IOhub
            eyetracker_config['local_edf_dir'] = self.filefolder                # otherwise this ends up in the main folder where the experiment itself lives
        else:
            print('no eyelink files should be stored')
            eyetracker_config['default_native_data_file_name'] = ''  # correct extention is added by IOhub
            eyetracker_config['local_edf_dir'] = ''                  # otherwise this ends up in the main folder where the experiment itself lives
```

This doesn't change anything for screen 1 and screen 2, but now pressing a key after screen 2 launches the calibration window, which is nice. Also a default edf file is created in ./

After leaving this window, I have a screen that's mostly black except the lower left quadrant (no idea why) so I can't see screen 3 but I'm assuming it's there. Then with another key it closes properly. Here is the log for the whole thing:
```
PS C:\Users\clementa\Desktop\templeton_gh\Distance> & "C:\Program Files\PsychoPy_2022\python.exe" .\ET_for_glasgow_test.py
pygame 2.1.0 (SDL 2.0.16, Python 3.8.10)
Hello from the pygame community. https://www.pygame.org/contribute.html
../data/distance/eyetracking/test/
test_dist_LH_1
True
displayAPI: init_net() start use_tcp_only=0
displayAPI: Connecting
IOHUB_DEVICE_EXCEPTION.Error: Could not retrieve sample rate modes from EyeLink Host. EyeTracker.setSamplingRate None
ERROR: setEyesToTrack: Failed to get supported modes.
pygame 2.1.0 (SDL 2.0.16, Python 3.8.10)
Hello from the pygame community. https://www.pygame.org/contribute.html
C:\Program Files\PsychoPy_2022\lib\site-packages\psychopy\visual\shape.py:251: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if value == "circle":
2.4107  WARNING         Monitor specification not found. Creating a temporary one...
2.4116  WARNING         Monitor specification not found. Creating a temporary one...
Calibration returned:  {'message': '', 'result': 1000}
file_size = 354
total_wbytes = 354
displayAPI: Disconnect
ioHub Server Process Completed With Code:  0
```

So overall there is some progress but also new issues.

**Comment by thartbm** [comment]
Removed need for extra window objects, resolving this issue as well.
